### PR TITLE
Whitelist journal storage writes as safe with a plone.protect > 3.0

### LINKED ISSUE #6: Whitelist journal storage writes as safe with a plone.protect > 3.0
Currently it is not possible to write to the journal in a get request with plone.protect > 3.0.

The fix for this is to conditionally mark the written objects as safe for writing when a suitable plone.protect is available.

### PR DESCRIPTION
**Pull request by Rotonen**
* Check for presence of safeWrite() in plone.protect
* Flag annotations as safe writes
* Flag workflow_history entries as safe writes
* Tests for write whitelisting are on the responsibility of the projects using plone.protect > 3.0

Fixes #6

### CODE REVIEW

**Comment by lukasgraf** [comment]
I don't think the `plone4.csrffixes` is required or beneficial. The way you install `plone4.csrffixes` already requires you to pin specific versions for those dependencies, as listed in the [`plone4.csrffixes` README](https://pypi.python.org/pypi/plone4.csrffixes).

That means that installing `plone4.csrffixes` is a very conscious decision, and has to be deliberately done on a per-project basis, where the version pinnings need to be handled anyway. Having to manage a dependency on `ftw.journal[plone4.csrffixes]` does nothing in the best case, and is more work otherwise.

**Comment by lukasgraf** [comment]
As for testing, *maybe* this could work: Always depend on `plone4.csrffixes` and the required recent enough dependencies from `test_require`, and disable/enable *automatic* CSRF protection on a per-test basis via the [`PLONE_CSRF_DISABLED` environment variable ](https://pypi.python.org/pypi/plone.protect#disable-all-automatic-csrf-protection)

**Comment by Rotonen** [comment]
There are deployments out there which do not want to have plone4.csrffixes at this point.

If we are to test both ways, we need segregability for plone4.csrffixes. The [extras] mechanism is a neat way to achieve this.

Do I amend the tests to test both ways or do I rip out the extras from setup.py?

**Comment by lukasgraf** [comment]
As discussed, 👍  for the extra (for use in tests / local development)

**Comment by lukasgraf** [comment]
@jone, if you guys are ok with this I'll go ahead and merge

**Pull request merged**
